default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: <%= ENV.fetch('PG_TIMEOUT') { 5000 } %>
  host: <%= ENV.fetch('PG_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('PG_USERNAME') { 'pguser' } %>
  password: <%= ENV.fetch('PG_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: guidetree/development

test: &test
  <<: *default
  database: guidetree/test

production:
  <<: *default
  database: guidetree/production

cucumber:
  <<: *test

